nodeLinker: pnp

packageExtensions:
  "@types/node@*":
    dependencies:
      events: "*"
      querystring: "*"
      url: "*"
      util: "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-airbnb-typescript@*:
    dependencies:
      eslint-config-airbnb-base: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  promise-inflight@*:
    dependencies:
      bluebird: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: strict

yarnPath: .yarn/releases/yarn-berry.cjs
