nodeLinker: pnp

pnpMode: loose

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  '@types/react@*':
    dependencies:
      prop-types: '*'
      scheduler: '*'
  '@types/node@*':
    dependencies:
      events: '*'
      url: '*'
      util: '*'
      querystring: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  eslint-config-airbnb-typescript@*:
    dependencies:
      eslint-config-airbnb-base: '*'
  promise-inflight@*:
    dependencies:
      bluebird: '*'
